name: Salus Security Scan

on: [pull_request, push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Salus Scan
      id: salus_scan
      uses: federacy/scan-action@0.1.4
      with:
        active_scanners: "\n  - PatternSearch\n  - Semgrep\n  - Trufflehog\n  - YarnAudit"
        salus_configuration: |
          scanner_configs:
            YarnAudit:
              exceptions:
                - advisory_id: 1102664
                  changed_by: sumxu96
                  notes: "Low severity DOM Clobbering vulnerability in tsup with no patch available"
