name: Salus Security Scan

on: [pull_request]

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Salus Scan
      id: salus_scan
      uses: federacy/scan-action@0.1.4
