name: Lint and Type-check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: TypeCheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn jest
