name: Unit Tests

on: [pull_request]

jobs:
  test:
    name: 'Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Unit Tests
        run: yarn jest
